// Generated by ts-to-zod
import { z } from "zod";

export const articleContentStackRealAclSchema = z.object({});

export const articleContentStackRealUrlSchema = z.object({
  url: z.string(),
  overridden: z.boolean(),
  useLangSub: z.boolean(),
});

export const articleContentStackRealPublishDetails2Schema = z.object({
  environment: z.string(),
  locale: z.string(),
  time: z.string(),
  user: z.string(),
});

export const articleContentStackRealPlaceHolderSchema = z.object({});

export const articleContentStackRealMetadataSchema = z.object({
  uid: z.string(),
});

export const articleContentStackRealSideImageSchema = z.object({
  image: articleContentStackRealPlaceHolderSchema,
  order: articleContentStackRealPlaceHolderSchema,
});

export const articleContentStackRealMetadata2Schema = z.object({
  uid: z.string(),
});

export const articleContentStackRealMetadata3Schema = z.object({
  uid: z.string(),
});

export const articleContentStackRealAcl2Schema = z.object({});

export const articleContentStackRealPublishDetailsSchema = z.object({
  environment: z.string(),
  locale: z.string(),
  time: z.string(),
  user: z.string(),
});

export const articleContentStackRealMetadata4Schema = z.object({
  uid: z.string(),
});

export const articleContentStackRealBannerSchema = z.object({
  _version: z.number(),
  is_dir: z.boolean(),
  uid: z.string(),
  ACL: articleContentStackRealAcl2Schema,
  content_type: z.string(),
  created_at: z.string(),
  created_by: z.string(),
  file_size: z.string(),
  filename: z.string(),
  parent_uid: z.string(),
  tags: z.array(articleContentStackRealPlaceHolderSchema),
  title: z.string(),
  updated_at: z.string(),
  updated_by: z.string(),
  publish_details: articleContentStackRealPublishDetailsSchema,
  url: z.string(),
});

export const articleContentStackRealBannerSettingsSchema = z.object({
  portrait_banner: articleContentStackRealPlaceHolderSchema,
});

export const articleContentStackRealRichTextEditorSchema = z.object({
  rich_text_editor: z.string(),
  _metadata: articleContentStackRealMetadataSchema,
  side_image: articleContentStackRealSideImageSchema,
});

export const articleContentStackRealSeparatorSchema = z.object({
  type: z.string(),
  custom_divider: articleContentStackRealPlaceHolderSchema,
  _metadata: articleContentStackRealMetadata2Schema,
});

export const articleContentStackRealAuthorBioSchema = z.object({
  author_selection: z.array(z.string()),
  _metadata: articleContentStackRealMetadata3Schema,
});

export const articleContentStackRealT2Schema = z.object({
  title: z.string(),
  _metadata: articleContentStackRealMetadata4Schema,
  image: articleContentStackRealPlaceHolderSchema,
});

export const articleContentStackRealArticleBodySchema = z.object({
  rich_text_editor: articleContentStackRealRichTextEditorSchema.optional(),
  separator: articleContentStackRealSeparatorSchema.optional(),
  author_bio: articleContentStackRealAuthorBioSchema.optional(),
});

export const articleContentStackRealChannelsConfigSchema = z.object({
  t2: articleContentStackRealT2Schema,
});

export const articleContentStackRealArticleSchema = z.object({
  _version: z.number(),
  locale: z.string(),
  uid: z.string(),
  ACL: articleContentStackRealAclSchema,
  _in_progress: z.boolean(),
  article_body: z.array(articleContentStackRealArticleBodySchema),
  article_tags: z.array(z.string()),
  article_type: z.string(),
  audience_targeting: z.array(articleContentStackRealPlaceHolderSchema),
  audience_targeting_boost: z.array(articleContentStackRealPlaceHolderSchema),
  author: z.array(z.string()),
  banner: articleContentStackRealBannerSchema,
  banner_settings: articleContentStackRealBannerSettingsSchema,
  category: z.array(z.string()),
  channels_config: z.array(articleContentStackRealChannelsConfigSchema),
  content_targeting_parameters: z.array(
    articleContentStackRealPlaceHolderSchema
  ),
  created_at: z.string(),
  created_by: z.string(),
  date: z.string(),
  description: z.string(),
  external_link: z.string(),
  hide_from_lol_com: z.boolean(),
  patch_notes_body: z.array(articleContentStackRealPlaceHolderSchema),
  promo_card_size: z.string(),
  send_mobile_push_notification: z.boolean(),
  send_to_mobile: z.boolean(),
  tags: z.array(articleContentStackRealPlaceHolderSchema),
  title: z.string(),
  updated_at: z.string(),
  updated_by: z.string(),
  url: articleContentStackRealUrlSchema,
  youtube_link: z.string(),
  publish_details: articleContentStackRealPublishDetails2Schema,
});
