// Generated by ts-to-zod
import { z } from "zod";

export const articleContentStackPartialDexAclSchema = z.object({});

export const articleContentStackPartialDexPublishDetailsSchema = z.object({
  environment: z.string(),
  locale: z.string(),
  time: z.string(),
  user: z.string(),
});

export const articleContentStackPartialDexRelatedSchema = z.object({
  _version: z.number(),
  locale: z.string(),
  uid: z.string(),
  ACL: articleContentStackPartialDexAclSchema,
  _in_progress: z.boolean(),
  created_at: z.string(),
  created_by: z.string(),
  date: z.string(),
  tags: z.array(z.string()).max(3), // only to generated controlled error
  title: z.string(),
  updated_at: z.string(),
  updated_by: z.string(),
  url: z.string(),
  publish_details: articleContentStackPartialDexPublishDetailsSchema,
});

export const relatedListResponseSchema = z.object({
  count: z.number(),
  entries: z.array(articleContentStackPartialDexRelatedSchema),
});
